// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TripAnalytics.API.Data;

#nullable disable

namespace TripAnalytics.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608071054_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TripAnalytics.API.Domain.Entities.TripSummary", b =>
                {
                    b.Property<string>("PostalCode")
                        .HasColumnType("character varying(10)");

                    b.Property<double>("AvgDistance")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgFare")
                        .HasColumnType("double precision");

                    b.Property<double>("DensityPerKm2")
                        .HasColumnType("double precision");

                    b.Property<int>("DropoffCount")
                        .HasColumnType("integer");

                    b.Property<int>("PickupCount")
                        .HasColumnType("integer");

                    b.HasKey("PostalCode");

                    b.ToTable("TripSummaries");
                });

            modelBuilder.Entity("TripAnalytics.API.Domain.Entities.ZipZone", b =>
                {
                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double>("AreaKm2")
                        .HasColumnType("double precision");

                    b.Property<string>("Borough")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PostalCode");

                    b.ToTable("ZipZones");
                });

            modelBuilder.Entity("TripAnalytics.API.Domain.Entities.TripSummary", b =>
                {
                    b.HasOne("TripAnalytics.API.Domain.Entities.ZipZone", "ZipZone")
                        .WithOne()
                        .HasForeignKey("TripAnalytics.API.Domain.Entities.TripSummary", "PostalCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZipZone");
                });
#pragma warning restore 612, 618
        }
    }
}
